apiVersion: v1
kind: Service
metadata:
  name: deepscale
spec:
  selector:
    app: deepscale
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepscale
  labels:
    app: deepscale
spec:
  selector:
    matchLabels:
      app: deepscale
  replicas: 1
  template:
    metadata:
      labels:
        app: deepscale
    spec:
      containers:
      - name: deepscale
        image: quay.io/codait/max-image-resolution-enhancer:latest
        ports:
        - containerPort: 5000
